### ISSUE TITLE
ESP8266 bin file is not created anymore

### ISSUE THREAD

**Issue by everslick** [plerup/makeEspArduino#101]
Since of today I cannot build binaries for ESP8266 anymore. Only the elf file is linked together and nothing more. 

I have set ESPTOOL_COM to the one in the Arduino-Core environment (i.e. tools/esptool/esptool). 

I don't see esptool being called at all (with VERBOSE=1).

**Comment by everslick** [comment]
I also tried setting ESPTOOL instead of ESPTOOL_COM. Made no difference. builds for ESP32 still work fine.

**Comment by plerup** [comment]
Syntax changes in the Arduino files again :unamused: 
Fix coming tonight

**Comment by plerup** [comment]
Please try latest version

**Comment by everslick** [comment]
Perfect! Thank you very much!!!
