### ISSUE TITLE
Makefile doesn't handle name clashes

### ISSUE THREAD

**Issue by cmarrin** [plerup/makeEspArduino#104]
I have an ESP Arduino project with a .ino file, uses core Arduino classes, some classes in sketches/libraries and my own custom library in a separate path. That custom library is added with CUSTOM_LIBS, which is a nice addition.

But my custom library has a Print.h/.cpp file, which clashes with the one in Arduino core.The Arduino core is placed in arduino.ar and included in the link like that, so there's no name clash in the link line. But because VPATH is used, whenever it looks for my Print.cpp it finds the one in the Arduino core.

I tried a few things but because of the complexity of where it's having to look for all the Arduino core components I wasn't able to come up with anything. My Makefile skills are not strong, so maybe someone else can think of something clever.

I renamed my class and now all is well, but it almost killed me. I've worked hard using namespaces and separate header directories to avoid this kind of issue. Every keystroke to change the name caused me physical pain :-)

**Comment by plerup** [comment]
Late response, sorry...
You could try the EXCLUDE_DIRS variable
