### ISSUE TITLE
Doesn't find correct ArduinoJson directory.

### ISSUE THREAD

**Issue by reitermarkus** [plerup/makeEspArduino#109]
I am using `ArduinoJson`, however the Makefile doesn't use the correct directory.

The Makefile uses the first directory, `~/Documents/Arduino/libraries/ArduinoJson`. The problem is that there are two header files:

- `~/Documents/Arduino/libraries/ArduinoJson/ArduinoJson.h`
- `~/Documents/Arduino/libraries/ArduinoJson/src/ArduinoJson.h`

Ideally, the directory for the second one should be preferred, since the first one also contains other directories aside from `src` containing `.h`/`.cpp` files, which aren't needed and fail to compile.

The obvious fix would be to change the `LIBS` script to prefer the `src` directory if the library has one. I would submit a PR, but I don't know Perl enough to change the script.

**Comment by fabiuz7** [comment]
It would be nice enhancement!
