### ISSUE TITLE
buindinfo.h docs

### ISSUE THREAD

**Issue by fabiuz7** [plerup/makeEspArduino#111]
Hi @plerup,
In your readme there is:

> The makefile will also automatically produce header and c files which contain information about the time when the build (link) was performed. This file also includes the git descriptions (tag) of the used version of the ESP/Arduino environment and the project source (when applicable). This can be used by the project source files to provide stringent version information from within the software.

But it took a while to understand how to use it in my project. I solved reading directly the makefile code.

A brief usage explanation could be useful for other users. I.e.

- _BuildInfo.src_version 
- _BuildInfo.date
- _BuildInfo.time
- _BuildInfo.env_version

**Comment by plerup** [comment]
Good point. Added in latest commit
