### ISSUE TITLE
Can't flash program on ESP32

### ISSUE THREAD

**Issue by fabiuz7** [plerup/makeEspArduino#112]
Hi,
I can't flash for ESP32 (tested with board variant d32). I cloned the last commit, but I can't make it work. Finally I've modified the [line](https://github.com/plerup/makeEspArduino/blob/master/makeEspArduino.mk#L90) with the following: 
ESPTOOL_PATH := $(lastword $(wildcard $(ARDUINO_ESP_ROOT)/tools/**esptool_py**/*))
I don't know why, but now I can compile for esp32, but not for esp8266.
Seems related to #102 ...

**Comment by plerup** [comment]
Please try latest commit

**Comment by fabiuz7** [comment]
That's perfect, thanks!
