### ISSUE TITLE
recipe for target 'flash' failed : pyserial usage ?

### ISSUE THREAD

**Issue by gd-git** [plerup/makeEspArduino#116]
Hi,

since I updated the Arduino (esp8266 / Arduino) and makeEspArduino directories the make flash command no longer works:
```
$ make flash
Error in command line, need pyserial path as 1st arg and esptool path as 2nd.
/home/toto/makeEspArduino/makeEspArduino.mk:294: recipe for target 'flash' failed
make: *** [flash] Error 1
```

My Makefile that worked before.

```
ARDUINO_ROOT=$(HOME)/arduino-1.8.8
ESP_ROOT=$(HOME)/Arduino
BOARD=nodemcuv2

include $(HOME)/makeEspArduino/makeEspArduino.mk
```
Everything works with an Arduino version (esp8266 / Arduino) of Fri May 4 17:18:15 2018 and have no other information on this regression.

With my thanks.

**Comment by plerup** [comment]
Please try latest commit

**Comment by everslick** [comment]
upload fails here as well with latest master of makeEspArduino and Arduino core:

```
Traceback (most recent call last):
  File "/home/clemens/Devel/ESP/emonio/src/../../Arduino-ESP8266/tools/upload.py", line 25, in <module>
    esptool.main(fakeargs)
TypeError: main() takes no arguments (1 given)
make[2]: *** [/home/clemens/Devel/ESP/emonio/src/../../makeEspArduino/makeEspArduino.mk:293: flash] Error 1
```

**Comment by plerup** [comment]
Are you using the latest version of this git?

And if you are using a git clone of Arduino core, have you cleaned up the mess of esptool versions by updating all submodules (update --init --recursive) and rerun get.py

**Comment by everslick** [comment]
> And if you are using a git clone of Arduino core, have you cleaned up the mess of esptool versions by updating all submodules (update --init --recursive) and rerun get.py 

No, I didn't. Thx for the pointer. I will report back!

**Comment by gd-git** [comment]
Hi,

sorry for the delay, everything works perfectly in my case with the latest version. Thank you because I can not do without makeEspArduino ;-)

**Comment by everslick** [comment]
Confirmed working!!! :+1:
