### ISSUE TITLE
Improve compatibility with Arduino building

### ISSUE THREAD

**Issue by fabiuz7** [plerup/makeEspArduino#117]
Hi,
I've observed a different behaviour between Arduino IDE compilation and your makefile.
Arduino IDE seems to compile only *.c/.cpp in sketch root folder andin  _src/_(recursively) folder.
Your makefile compiles everything recursively starting from sketch root.

Is it possibile to emulate the Arduino behaviour?

I've also tried:
`EXCLUDE_DIRS = 	$(SKETCH_DIR)/foo`
to exclude a file foo/bar.cpp, but it doesn't do anything (i.e. foo/bar.cpp is compiled as usual)

**Comment by plerup** [comment]
Try using:
EXCLUDE_DIRS=./foo
