### ISSUE TITLE
/bin/sh: 1: /python: not found

### ISSUE THREAD

**Issue by gpepe** [plerup/makeEspArduino#122]
make DEMO=1
Linking /tmp/mkESP/HelloServer_generic/HelloServer.bin
  Versions: Unknown, 2.5.2
/bin/sh: 1: /python: not found
Makefile:284: recipe for target '/tmp/mkESP/HelloServer_generic/HelloServer.bin' failed
make: *** [/tmp/mkESP/HelloServer_generic/HelloServer.bin] Error 127

**Comment by richardh538** [comment]
So how was it solved?
