### ISSUE TITLE
Question: Secure Boot + Flash Encryption?

### ISSUE THREAD

**Issue by ElVasquito** [plerup/makeEspArduino#127]
Sorry if this is the wrong place to ask.
Is it possible to compile and also enable Secure Boot + Flash Encryption with makeEspArduino?

**Comment by plerup** [comment]
Never used it myself but makeEspArduino only handles the options available for ESP32 Arduino and I haven't seen any mention of it there, only in the SDK

**Comment by ElVasquito** [comment]
Okay, thanks for replying!
