### ISSUE TITLE
make flash! python3: not found (ESP8266)

### ISSUE THREAD

**Issue by everslick** [plerup/makeEspArduino#128]
Is it only me? make insists on finding python3 in the tools directory:
```
Linking ../build/3.0.99/borabora/eng/alpha/emonio.bin
  Versions: 3.0.25-29-g5a06ffd, 2.5.2-205-g6e51ef0c
/bin/sh: 1: ../../Arduino-ESP8266/tools/python3/python3: not found
make[1]: *** [../../makeEspArduino/makeEspArduino.mk:299: ../build/3.0.99/borabora/eng/alpha/emonio.bin] Error 127
```
Makefile is up to date:
```
clemens@secrets:~/Devel/ESP$ cd makeEspArduino/
clemens@secrets:~/Devel/ESP/makeEspArduino$ git pull origin master 
From github.com:plerup/makeEspArduino
 * branch            master     -> FETCH_HEAD
Already up to date.
```
python is in $PATH:
```
clemens@secrets:~/Devel/ESP/makeEspArduino$ which python
/usr/bin/python
clemens@secrets:~/Devel/ESP/makeEspArduino$ which python3
/usr/bin/python3
```

**Comment by plerup** [comment]
This looks like the problem which was fixed in the latest commit. Are you sure you are running from the git you show above?

**Comment by everslick** [comment]
100% positive. I have no other repo checked out.

**Comment by plerup** [comment]
Try the DEMO=1 variant

**Comment by plerup** [comment]
By the way you use the IGNORE_STATE don't you? Do a clean then and build again

**Comment by everslick** [comment]
yes, `IGNORE_STATE = 1`. make clean does NOT help.

**Comment by plerup** [comment]
What about DEMO=1 ?

**Comment by everslick** [comment]
```
Linking ../build/3.0.99/borabora/eng/alpha/HelloServer.bin
  Versions: 2.5.2-205-g6e51ef0c, 2.5.2-205-g6e51ef0c
/bin/sh: 1: ../../Arduino-ESP8266/tools/python3/python3: not found
```

**Comment by plerup** [comment]
Well, then I'm lost works flawlessly here

   Linking /tmp/mkESP/HelloServer_generic/HelloServer.bin
     Versions: 2.5.2-206-g7a43092d, 2.5.2-206-g7a43092d
   Creating BIN file "/tmp/mkESP/HelloServer_generic/HelloServer.bin" using 
   "/tmp/mkESP/HelloServer_generic/HelloServer.elf"

**Comment by plerup** [comment]
"git status" perhaps to make sure

**Comment by everslick** [comment]
dammit! you got me. my HEAD was detached. obviously not only my git HEAD but also me real one.

sorry for wasting your time.

**Comment by everslick** [comment]
what i do not understand is, that i EXPLICITLY checked out commit 1cbe5fe. more specific I do:

cd ../makeEspArduino
git pull origin master
git checkout 1cbe5fe

It seems as this does not do what I thought it would do.

**Comment by everslick** [comment]
OK, before I go nuts, can you pls check that `make flash` works?

**Comment by plerup** [comment]
Works here...

**Comment by everslick** [comment]
thx, which OS?

**Comment by plerup** [comment]
Ubuntu 18.04

**Comment by plerup** [comment]
Ok, this may be an error.
I have esptool.py in my path
Investigating

**Comment by plerup** [comment]
Ok, I can see that links to python is now created by ESP8266-Arduino when running the "get.py" script in the tools directory, so you must run this whenever that git is updated :see_no_evil:

**Comment by everslick** [comment]
OMG, never would have guessed that. THX!

nevertheless, the fun does not stop there. it does not honor SERIAL_PORT=/dev/ttyUSBX anymore for me...
```
clemens@secrets:~/Devel/ESP/emonio-fw$ make MODEL=borabora SERIAL_PORT=/dev/ttyUSB0 usb VERBOSE=1
make flash
make[2]: Entering directory '/home/clemens/Devel/ESP/emonio-fw/src'
"../../Arduino-ESP8266/tools/python3/python3" "../../Arduino-ESP8266/tools/upload.py" --chip esp8266 --port "/dev/ttyUSB1" --baud "115200"  version --end --chip esp8266 --port "/dev/ttyUSB1" --baud "115200"  write_flash 0x0 "../build/3.0.99/borabora/eng/alpha/emonio.bin" --end
esptool.py v2.7
2.7
esptool.py v2.7
Serial port /dev/ttyUSB1
Connecting......
```

**Comment by plerup** [comment]
UPLOAD_PORT is the correct variable

**Comment by everslick** [comment]
oh, indeed. THX so much!

**Comment by everslick** [comment]
`make erase_flash` has a similar problem :-(

```
/bin/sh: 1: /../../Arduino-ESP8266/tools/python3/python3: not found
make[1]: *** [../../makeEspArduino/makeEspArduino.mk:365: erase_flash] Error 127
```

the path now has a leading **/**

**Comment by plerup** [comment]
What value are you setting for ESP_ROOT?

**Comment by everslick** [comment]
ESP_ROOT = ../../Arduino-ESP8266

```
clemens@secrets:~/Devel/ESP/emonio-fw/src$ ls ../../Arduino-ESP8266
bootloaders  doc        package  tools     boards.txt         keywords.txt  package.json  POLICY.md        README.md
cores        libraries  tests    variants  ISSUE_TEMPLATE.md  LICENSE       platform.txt  programmers.txt
```

**Comment by everslick** [comment]
it is the same for all build targets.

**Comment by plerup** [comment]
Ok, this seems to be an error. It's a constant struggle trying to keep up with the constant changes in the arduino platform.txt 
Fix is coming

**Comment by plerup** [comment]
Workaround in the mean time is to do

pip install esptool

**Comment by everslick** [comment]
thx, once more!

**Comment by plerup** [comment]
Ok, the handling of esptool in esp8266/Arduino is really a mess right now. I will make installation of esptool.py a requirement for some of the flashing operations. If missing an error message will be shown explaining this.

New version available now

**Comment by everslick** [comment]
Thank you! :1st_place_medal:
