### ISSUE TITLE
LWIP Variant

### ISSUE THREAD

**Issue by alphabeta1212** [plerup/makeEspArduino#136]
Hi, How do I change the LWIP variant using this environment? I am facing an issue where the TCP send buffer is very low, almost 1KB. I believe changing the variant from v2 Lower memory to Higher bandwidth will be helpful. I have tried changing the lwipopts.h , opt.h of both versions and still not able to see a change in the stack size.  

Please help.

**Comment by plerup** [comment]
You can get information on this via the "help" option
make -f makeEspArduino.mk help

**Comment by alphabeta1212** [comment]
Thank you, really appreciate your quick replies, It worked.
