### ISSUE TITLE
ESP32 builds stopped working after change to platform.txt in arduino-esp32 project

### ISSUE THREAD

**Issue by AdrianEddy** [plerup/makeEspArduino#142]
When trying to build ESP32 project, only .elf file is created and .bin file is not created, causing the build to fail.

This happened after parameter rename in esp32 project in platform.txt: https://github.com/espressif/arduino-esp32/commit/831f0ac29af1e2f7d174875a5e88d8ab1d97bd95 
It caused ```GEN_PART_COM``` and ```ELF2BIN_COM``` variables to be empty

**Comment by plerup** [comment]
Fixed in latest commit
Thanks for reporting

**Comment by AdrianEddy** [comment]
Thank you, it works now 👍
