### ISSUE TITLE
Cannot compile simple project for ESP8266

### ISSUE THREAD

**Issue by petrstetina** [plerup/makeEspArduino#154]
`cannot open linker script file local.eagle.flash.ld: No such file or directory`

Tested with latest git version of esp8266 Arduino

The root cause of the issue is probably missing support for additional recipe.hooks.linking.prelink patterns (2 - 4) and also parsing of mmuflags from boards.txt

**Comment by plerup** [comment]
Fixed in latest commit
Thanks for reporting
