### ISSUE TITLE
[question] Is there a way to set the speed of a esp8266 to 160MHz?

### ISSUE THREAD

**Issue by linuxcult** [plerup/makeEspArduino#159]
I'm not a pro at all, so please be patient, if I get something wrong.

I just want to know, if there's a way to set the speed of a ESP8266 to 160MHz with makeEspArduino?

Until now I need  to use the Arduino IDE to upload my sketch if I want to set the speed.

Thanks.

**Comment by plerup** [comment]
Define this variable:

    F_CPU=160000000L

**Comment by linuxcult** [comment]
Jep, that did the trick! 

Thank you very much!
