### ISSUE TITLE
make flash_fs fails on version 6.4.0

### ISSUE THREAD

**Issue by juanolete** [plerup/makeEspArduino#167]
Hi, when I use the command:
`espmake flahs_fs`

The esptool show me the following error:

=== Using upload port: /dev/FTDIProg-0 @ 115200
`/home/pi/esp8266/tools/python3/python3 /home/pi/makeEspArduino/tools/py_wrap.py /home/pi/esp8266/tools esptool --baud=115200 --port /dev/FTDIProg-0 --chip esp8266 ---before default_reset --after hard_reset write_flash 0x200000 /tmp/mkESP/wenu_nodemcuv2/FS.bin`

usage: esptool [-h] [--chip {auto,esp8266,esp32}] [--port PORT] [--baud BAUD]
               [--before {default_reset,no_reset,no_reset_no_sync}]
               [--after {hard_reset,soft_reset,no_reset}] [--no-stub]
               [--trace] [--override-vddsdio [{1.8V,1.9V,OFF}]]
               {load_ram,dump_mem,read_mem,write_mem,write_flash,run,image_info,make_image,elf2image,read_mac,chip_id,flash_id,read_flash_status,write_flash_status,read_flash,verify_flash,erase_flash,erase_region,version}
...

`esptool: error: argument operation: invalid choice: 'default_reset' (choose from 'load_ram', 'dump_mem', 'read_mem', 'write_mem', 'write_flash', 'run', 'image_info', 'make_image', 'elf2image', 'read_mac', 'chip_id', 'flash_id', 'read_flash_status', 'write_flash_status', 'read_flash', 'verify_flash', 'erase_flash', 'erase_region', 'version')
make: *** [/home/pi/makeEspArduino/makeEspArduino.mk:354: flash_fs] Error 2`

This is due to the `---before` option on the esptool command, on the version 6.3.1 this error doesn't occur.

Can you fix it, please.

Thanks!

**Comment by plerup** [comment]
Fixed, thanks for reporting
