### ISSUE TITLE
Getting Xtensa Error

### ISSUE THREAD

**Issue by uniquenepalhumepipe** [plerup/makeEspArduino#182]
I am getting this error ```
- Parsing Arduino configuration files ...
- Finding all involved files for the build ...
- Parsing Arduino configuration files ...
BearSSLHelpers.cpp
CertStoreBearSSL.cpp
xtensa-lx106-elf-g++: error: {runtime.platform.path}/tools/warnings/none-g++: No such file or directory
xtensa-lx106-elf-g++: error: {runtime.platform.path}/tools/warnings/none-g++: No such file or directory
make: *** [makeEspArduino.mk:273: /tmp/mkESP/WiFiScan_generic/BearSSLHelpers.cpp.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [mak
```

**Comment by plerup** [comment]
This was due to new handling of warnings in the latest commit in esp8266/Arduino

Fixed here in the latest commit
