### ISSUE TITLE
Variant ESP32 devices

### ISSUE THREAD

**Issue by basepr1me** [plerup/makeEspArduino#185]
Howdy, I'm working on some new OpenBSD toolchains for ESP32-S2/S3/C3. On line 131, the following is defined:

ESPTOOL_COM ?= $(ESPTOOL) --baud=$(UPLOAD_SPEED) --port $(UPLOAD_PORT) --chip $(CHIP)

However, for variant devices, --chip must follow the BOARD= setting: esp32s2, esp32s3, esp32c3. Of course, setting CHIP= to anything other than esp32 alters the folders that are defined for the arduino hardware toolchain, resulting in error.

You can see the output here:

```
stef$ espmake32 BOARD=esp32c3 ESPTOOL=esptool.py VERBOSE=1 erase_flash
=== Using upload port: /dev/ttyU0 @ 921600
esptool.py --baud=921600 --port /dev/ttyU0 --chip esp32 erase_flash
esptool.py v4.1
Serial port /dev/ttyU0
Connecting...
Failed to get PID of a device on /dev/ttyU0, using standard reset sequence.
.

A fatal error occurred: This chip is ESP32-C3 not ESP32. Wrong --chip argument?
gmake: *** [/usr/local/share/makeEspArduino/makeEspArduino.mk:401: erase_flash] Error 2
```
Any thoughts on how to best fix this would be much appreciated.
Thanks.

**Comment by plerup** [comment]
For now you can get around the problem by adding the correct definition of ESPTOOL_COM on the command line or in your project config.mk.
Fix will come in next version.
