### ISSUE TITLE
multiple definition of `_BuildInfo'

### ISSUE THREAD

**Issue by gpancot** [plerup/makeEspArduino#19]
using "#include \<buildinfo.h\>",  first make is ok.
subsequent fail with:

Linking ./getVcc-Udp_httpUpd_generic/getVcc-Udp_httpUpd.bin
  Versions: f735ecd-dirty, 2.3.0
./getVcc-Udp_httpUpd_generic/buildinfo.cpp.o:(.data._BuildInfo+0x0): multiple definition of `_BuildInfo'
getVcc-Udp_httpUpd_generic/buildinfo.cpp.o:(.data._BuildInfo+0x0): first defined here
collect2: error: ld returned 1 exit status

work ok with:

--- makeEspArduino.mk.org       2016-09-08 11:35:27.703833609 +0200
+++ makeEspArduino.mk   2016-09-08 11:35:14.764098070 +0200
@@ -158,7 +158,7 @@
 # Automatically generated build information data
 # Makes the build date and git descriptions at the actual build event available as string constants in the program
 BUILD_INFO_H = $(BUILD_DIR)/buildinfo.h
-BUILD_INFO_CPP = $(BUILD_DIR)/buildinfo.cpp
+BUILD_INFO_CPP = $(BUILD_DIR)/buildinfo.c++

**Comment by plerup** [comment]
This is due to the fact that you have put your build directory as a sub-directory to the sketch directory.

Good suggested fix though.
