### ISSUE TITLE
Problems with include path

### ISSUE THREAD

**Issue by tpso1965** [plerup/makeEspArduino#192]
After upgrading to current version compiling fails because include files in ./libraries/xxx/src is not in include path any longer.

I have a project with a local version of a mqtt-library pleaced in ./libraries.  Ths sources in ./src contains include written as
#include <PubSubClient.h>.

This worked fine with my previous version of makeEspArduino - but after update compilation fails with
PubSubClient.h not found.

**Comment by plerup** [comment]
Please provide some more details about your setup

**Comment by tpso1965** [comment]
All my projects have a standard set with the following directory layout:


projectX/src    (directory with the project source-files)
projectX/libraries   (extra libraries local for THIS project)
projectX/makefile



I have attached 3 makefiles:  makefile.org  that was the simple one that worked before upgrade, and a
hacked one, where I have to specify each library, to get it working.

[makefile_org.txt](https://github.com/plerup/makeEspArduino/files/11494575/makefile_org.txt)

[makefile_hacked.txt](https://github.com/plerup/makeEspArduino/files/11494576/makefile_hacked.txt)

**Comment by plerup** [comment]
Try changing the CUSTOM_LIBS definition to the full path or at least ./libraries

**Comment by tpso1965** [comment]
Tried to set CUSTOM_LIBS to both ./libraries and full path   - no difference.
If I dont set INCLUDE_DIRS for each library I get compile error like:

fatal error: Adafruit_Sensor.h: No such file or directory
 #include <Adafruit_Sensor.h>

If I set alle the INCLUDE_DIRS it compiles fine.

The error occur while the makefile compiles the **library** - I dont know if that is worth noting - Is compiling the libraries handled diffrently from compiling the project source ?

**Comment by plerup** [comment]
This works for me at least:

    CUSTOM_LIBS = $(realpath libraries)

**Comment by tpso1965** [comment]
The "realpath" did it - it worked.

Thank you!

**Comment by plerup** [comment]
Used automatically in latest version
