### ISSUE TITLE
WiFi firmware update support

### ISSUE THREAD

**Issue by p1er** [plerup/makeEspArduino#21]
Does the makefile support WiFi firmware upload?
It is _much_ faster than the serial upload and also allows for automated updates.
The arduino WiFi upload works like a charm, and from what I gather it mostly uses external tools, so it should not be that hard to make it work on for makeEspArduino.

**Comment by plerup** [comment]
Yes, two targets are available for this:

http: Update via curl
ota: Update via espota.py

You just have to define the parameters, see the start of the makefile
