### ISSUE TITLE
How to set output directory relative to the sketch

### ISSUE THREAD

**Issue by kommancs96** [plerup/makeEspArduino#24]
I made an alias for the `makeEspArduino.mk` file as described in the readme. Now i want to change the makefile so that it produces a binary in the `/buid` folder next to the sketch. So if I have the sketch at `~/Documents/sketches/mySketch/fiest.ino` , the output should be placed at `~/Documents/sketches/mySketch/build/first.bin`

**Comment by plerup** [comment]
Use:

**BUILD_DIR=./build**

Either in a config.mk or on the command line.

Just make sure to use the latest version though, 3.2.2

**Comment by kommancs96** [comment]
Hello  I tried to modify the makefile so: `BUILD_DIR ?= $(dir $(shell pwd)/build)` , but this did not work.

**Comment by plerup** [comment]
Ok, what happened then?

**Comment by kommancs96** [comment]
It compiles in the same directory where the sketch is.

**Comment by plerup** [comment]
Should be:

BUILD_DIR ?= $(dir $(shell pwd)/build/)
BUILD_DIR ?= $(shell pwd)/build

or preferably the solution I suggested in my first comment which doesn't require a change in the original makefile

**Comment by kommancs96** [comment]
This worked, I close this issue.
