### ISSUE TITLE
Add a way to exclude directories

### ISSUE THREAD

**Issue by sluebbert** [plerup/makeEspArduino#27]
Any test files that reside with your included directories (USER_INC) or source directories (USER_SRC) get automatically grabbed when building.  I have files where I mock the EEPROM.h or specify test definitions for example that I certainly don't want the makefile to grab just because they sit inside my project directory under the folder test/.  Today I have to modify the makefile or move all testing away from my projects.  A supported way to have a list of exclusions would be a nice to have!

**Comment by plerup** [comment]
Added in latest commit

**Comment by sluebbert** [comment]
Awesome works great!
