### ISSUE TITLE
add reset metod to esptool

### ISSUE THREAD

**Issue by gpancot** [plerup/makeEspArduino#3]
to enable other reset methods I defined:

UPLOAD_RESET ?= nodemcu

and modified:

upload: all
    $(ESP_TOOL) $(UPLOAD_VERB) -cd $(UPLOAD_RESET) -cb $(UPLOAD_SPEED) -cp $(UPLOAD_PORT) -ca 0x00000 -cf $(MAIN_EXE)

**Comment by plerup** [comment]
Good idea

**Comment by plerup** [comment]
Committed now
