### ISSUE TITLE
Why is  $(HOME)/Arduino/libraries not searched automatically?

### ISSUE THREAD

**Issue by mknj** [plerup/makeEspArduino#33]
The Libs that are installed by arduino(linux,1.8.2) -> sketch -> include library -> manage libraries are not found automatically.

workaround:

+ESP_LIBS2 = $(HOME)/Arduino/libraries

+  LIBS += $(shell perl -e 'use File::Find;$$d = shift;while (<>) {$$f{"$$1"} = 1 if /^\s*\#include\s+[<"]([^>"]+)/;}find(sub {print $$File::Find::dir," " if $$f{$$_}}, $$d);'  $(ESP_LIBS2) $(SKETCH))

**Comment by plerup** [comment]
Good idea, fixed in latest commit
