### ISSUE TITLE
Finding custom arduino directory

### ISSUE THREAD

**Issue by matthewg42** [plerup/makeEspArduino#36]
I moved my arduino/libraries directory to a non-standard location, and updated sketchbook.path in my $HOME/.arduino15/preferences.txt file, but it is not being picked up by the makefile.  I made a patch to fix this, which is attached.

[custom_arduino_path.patch.txt](https://github.com/plerup/makeEspArduino/files/993108/custom_arduino_path.patch.txt)

**Comment by matthewg42** [comment]
Note: only tested on Linux - I don't have a windows or OSX environment to test this on, sorry!

**Comment by plerup** [comment]
Fixed in latest commit
