### ISSUE TITLE
Proposal: adding $(LD_EXTRA)

### ISSUE THREAD

**Issue by everslick** [plerup/makeEspArduino#46]
I would like to propose the addition of the variable LD_EXTRA for giving extra linker flags.

by changing:

$(LD_COM)

to:

$(LD_COM) $(LD_EXTRA)

I use this to wrap functions from the Core. Very useful.

**Comment by plerup** [comment]
Good point, will be added

**Comment by plerup** [comment]
Done in latest version

**Comment by everslick** [comment]
Thanks!
