### ISSUE TITLE
Adding all sourcefiles in Sketch directory when LIBS variable is not defined

### ISSUE THREAD

**Issue by WooWapDaBug** [plerup/makeEspArduino#50]
Thanks for such a great tool!
I want to have my own folder structure and I was tweaking the Makefile a little bit, just found a small issue when the LIBS variable is empty:

ifneq ($(LIBS),)
	USER_SRC := $(SKETCH) $(filter-out $(IGNORE_PATTERN),$(shell find $(dir $(LIBS)) -name "*.S" -o -name "*.c" -o -name "*.cpp"))
else
	USER_SRC := $(SKETCH)
endif

When LIBS variable is empty (which was my case), it tries to compile all source files under the Makefile directory. So I added a simple check to assure it is not empty.

**Comment by plerup** [comment]
Well, LIBS should normally not be empty but if there are no #includes in the sketch I realize that it may get that.
Good point.
