### ISSUE TITLE
Proposal: Progress bar during OTA upload

### ISSUE THREAD

**Issue by everslick** [plerup/makeEspArduino#51]
By adding -r to the parameters to OTA_TOOL we get a nice progress bar during upload instead of those pesky dots.

change line 246 from:

$(OTA_TOOL) -i $(ESP_ADDR) -p $(ESP_PORT) -a $(ESP_PWD) -f $(MAIN_EXE)

to:

$(OTA_TOOL) -r -i $(ESP_ADDR) -p $(ESP_PORT) -a $(ESP_PWD) -f $(MAIN_EXE)

**Comment by plerup** [comment]
:+1:

**Comment by plerup** [comment]
Done in latest commit
