### ISSUE TITLE
setting ARDUINO_ARCH_

### ISSUE THREAD

**Issue by vitoller** [plerup/makeEspArduino#52]
I am using the make file under linux (ubuntu), from a project originally set up with platformio (atom).

One of the projects uses the RingBuffer library.
    https://github.com/wizard97/ArduinoRingBuffer

The library checks the architecture:
    #elif defined(ARDUINO_ARCH_ESP8266)

with the makefile the architecture is set to:
ARDUINO_ARCH_esp8266

as a workaround I added:
BUILD_EXTRA_FLAGS = -DARDUINO_ARCH_ESP8266

Is there a better way of doing this?

**Comment by plerup** [comment]
This is a bug. Will be fixed in next commit

**Comment by plerup** [comment]
Done

**Comment by vitoller** [comment]
great! thanks for the quick fix

**Comment by dopefishh** [comment]
This bug resurfaced at some point because with the latest greatest tip it is again ARDUINO_ARCH_esp8266.
