### ISSUE TITLE
spaces in library directories

### ISSUE THREAD

**Issue by vitoller** [plerup/makeEspArduino#53]
I am using the make file under linux (ubuntu), from a project originally set up with platformio (atom).

The libraries imported from platformio can include spaces:

.piolibdeps/Adafruit Unified Sensor_ID31

When adding the directory to the libraries (LIBS) to project, the directory is not fully recognized.

As a workaround I have renamed the directories not to have spces.

Is there a better way to do this?

**Comment by plerup** [comment]
Currently not. There are many parts of the makefile which assume that space is a separator.
Maybe it ought to be fixed...

**Comment by vitoller** [comment]
ok.
The workaround is fine for me.
