### ISSUE TITLE
BOARD variable doesn't accept boards name with parenthesis

### ISSUE THREAD

**Issue by amontefusco** [plerup/makeEspArduino#55]
Selecting as board name NodeMCU 0.9 (ESP-12 Module) the make fails as follows:

~/makeEspArduino$ make -f ~/makeEspArduino/makeEspArduino.mk ~/Arduino/ESP8266-WiMgr-AutoConnectWithTelegram/ESP8266-WiMgr-AutoConnectWithTelegram.ino BOARD='NodeMCU 0.9 (ESP-12 Module)'
/bin/sh: 1: Syntax error: "(" unexpected
* Build state has changed, doing a full rebuild *
/bin/sh: 1: Syntax error: "(" unexpected
/bin/sh: 1: Syntax error: "(" unexpected
make: *** /tmp/mkESP/HelloServer_NodeMCU: Is a directory.  Stop.

even using escape backslashes I got similar errors.

**Comment by plerup** [comment]
That is the explanatory name for this board. The real name is **nodemcu**

Use the target list_boards to get all available boards

make -f ~/makeEspArduino/makeEspArduino.mk list_boards
