### ISSUE TITLE
add a $(CUSTOM_DEPENDS) for user dependecies

### ISSUE THREAD

**Issue by nemo9955** [plerup/makeEspArduino#57]
Add an empty variable like `"$(CUSTOM_DEPENDS) $(ESP_LIBS) $(ARDUINO_LIBS)" $(SKETCH))` at the end of the `LIBS :=` initialization so a user can include his custom libraries alongside the Arduino and ESP ones.

Personally, I thought that is what LIBS was for (specifying some general libs that may be a dependency ) , but looking at the source, LIBS is for the EXACT libs to be compiled.

**Comment by everslick** [comment]
I do it by providing the path, like this:
```
LIBS       = ../libs/WebServer             \
             $(ESP_LIBS)/ESPmDNS           \
             $(ESP_LIBS)/HTTPClient
 ```
Unless i misunderstand, what your goal is.

**Comment by nemo9955** [comment]
I have a few sketches with different imports; I don't want to manually give it the path from every library for every sketch, since this makefile automatically searches the needed libs from the `import<*>` statement from a "pool" of libraries: ESP_LIBS and ARDUINO_LIBS.

**Comment by plerup** [comment]
New variable CUSTOM_LIBS added in latest commit. Enables automatic search for library dependencies in additional directories.
