### ISSUE TITLE
makefile seems to launch all compiles in parallel

### ISSUE THREAD

**Issue by vortex314** [plerup/makeEspArduino#62]
When using this makefile I observe 2 behaviours :+1: 
1/ It launches all compiles in parallel, putting my PC out of memory and freezes the user interface
2/ All files are recompiled , even when not changed

Is this expected behaviour ?

**Comment by plerup** [comment]
1) This is intended as it normally speeds up the build. Can be avoided by adding SINGLE_THREAD=1
2) Definitely not. What OS are you on?

**Comment by vortex314** [comment]
Thanks for the swift response ! 
I'm running on : Linux pchp 4.8.0-59-generic #64-Ubuntu SMP Thu Jun 29 19:38:34 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
