### ISSUE TITLE
Recursive header include

### ISSUE THREAD

**Issue by nemo9955** [plerup/makeEspArduino#72]
I flashed a sketch with this makefile and everything worked, but after creating a library for that sketch's contents I ran into 2 problems :

1. .hpp files are not taken into consideration, easy fix: `USER_INC := $(filter-out $(IGNORE_PATTERN),$(call find_files,hpp|h,$(SKETCH_DIR) $(dir $(LIBS))))`

2. Headers inside the lib do not seem to be included
`fatal error: ESPAsyncTCP.h: No such file or directory`
If I add `#include <ESPAsyncTCP.h>` in the .ino it includes it ... but then `fatal error: TaskScheduler.h: No such file or directory`
Including core headers like `#include <inttypes.h>` seem to work inside the lib thou.
All the dependent libs are passed to the makefile using `CUSTOM_LIBS=` like in  #57  (including this "new" lib)

**Comment by wintersandroid** [comment]
Thanks for the hpp tip, I have been trying to use makeEspArduino with a project that uses the ArduinoJson library, this solves one problem (the hpp files)
