### ISSUE TITLE
unable to compile on windows

### ISSUE THREAD

**Issue by sanu-krishnan** [plerup/makeEspArduino#78]
I tried the make command on windows 
`make -f makeEspArduino.mk ESP_ROOT=esp CHIP=esp32 DEMO=1` and got following error !
Tried on both 32 bit and 64 bit versions of cygwin

```
/usr/bin/sh: perl: command not found
/usr/bin/sh: perl: command not found
/usr/bin/sh: /proc/1/cmdline: No such file or directory
FIND: Parameter format not correct
/usr/bin/sh: perl: command not found
/usr/bin/sh: perl: command not found
/usr/bin/sh: perl: command not found
make: *** No rule to make target `C:/cygwin/tmp/mkESP/WiFiScan_esp32/arduino.mk', needed by `all'.  Stop.

```

the same procedure works fine in Ubuntu, and I am able to download the code to esp32 board as well. What is the mistake I did in windows? 

![image](https://user-images.githubusercontent.com/38312605/39297711-e4c384c6-494c-11e8-9a25-b4c78666a276.png)

**Comment by plerup** [comment]
You need to install Perl in your cygwin setup

**Comment by sanu-krishnan** [comment]
That works. Thank you
