### ISSUE TITLE
eagle.app.v6.common.ld was removed from ESP8266 SDK

### ISSUE THREAD

**Issue by everslick** [plerup/makeEspArduino#80]
https://github.com/esp8266/Arduino/commit/d582cab938f041f622f2d4d8016b3d4bada55580

The common linker file was removed from the ESP8266 SDK and now is supposed to be auto-generated through the build process. I think it depends on, if the user wants to have the VTABLES be stored in RAM or on flash. but i'm not sure how this works.

**Comment by everslick** [comment]
AFAIKS, it is now abusing the precompiler to generate the correct linker script:

platform.txt:
```
## Build the app.ld linker file                                                 
recipe.hooks.linking.prelink.1.pattern="{compiler.path}{compiler.c.cmd}" -CC -E -P {build.vtable_flags} "{runtime.platform.path}/tools/sdk/ld/eagle.app.v6.common.ld.h " -o "{runtime.platform.path}/tools/sdk/ld/eagle.app.v6.common.ld"
```

should then be something like this (PSEUDO) rule:
```
eagle.app.v6.common.ld: eagle.app.v6.common.ld.h eagle.app.v6.common.ld.vtable.h
   $(CC) -CC -E -P ${VTABLE_FLAGS} -o eagle.app.v6.common.ld
```

**Comment by plerup** [comment]
Fixed in latest commit
