### ISSUE TITLE
Linking fails with latest ESP8266 Arduino Core.

### ISSUE THREAD

**Issue by everslick** [plerup/makeEspArduino#89]
The linker is called with an empty script, but the -T option is present:

```
"../../Arduino-ESP8266/tools/xtensa-lx106-elf/bin/xtensa-lx106-elf-gcc" -Wl,-Map "-Wl,../build/3.0.99/ahe/eng/alpha/emonio.map" -g -w -Os -nostdlib -Wl,--no-check-sections -u app_entry -u _printf_float -u _scanf_float -Wl,-static "-L../../Arduino-ESP8266/tools/sdk/lib" "-L../../Arduino-ESP8266/tools/sdk/ld" "-L../../Arduino-ESP8266/tools/sdk/libc/xtensa-lx106-elf/lib" "-T" -Wl,--gc-sections  ....
```

error is:

```
/home/clemens/Devel/ESP/Arduino-ESP8266/tools/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld: cannot open linker script file -Wl,--gc-sections: No such file or directory
collect2: error: ld returned 1 exit status
../../makeEspArduino/makeEspArduino.mk:251: recipe for target '../build/3.0.99/ahe/eng/alpha/emonio.bin' failed

```

**Comment by plerup** [comment]
Are you using the latest version of makeEspArduino (4.14.2)?

**Comment by everslick** [comment]
Hmm... Maybe my FLASH_DEF is not set correctly... Hang on...

**Comment by plerup** [comment]
Strange, works for me (esp8266 Arduino 2.4.2-83-g64dd492) and this was one of the things fixed in latest commit. 
What happens if you do the demo build (DEMO=1)

**Comment by everslick** [comment]
OK, sorry for bothering you. It really was the FLASH_DEFS variable. It was set to 1M0 instead of 1M, because this used to be the correct linker script once. I should have checked better before opening an issue. -> closing
