### ISSUE TITLE
erase_flash does not honor $(ESPTOOL_PY)

### ISSUE THREAD

**Issue by everslick** [plerup/makeEspArduino#91]
i set a custom path to the ESPTOOL_PY tool which gets picked correctly when `make flash` is called, but not when i call `make erase_flash`

```
clemens@secrets:~/Devel/ESP/emonio/src$ make erase_flash
Using: /dev/ttyUSB0 @ 921600
/bin/sh: 1: ../../Arduino-ESP32-espressif/tools/esptool/esptool.py: Permission denied
../../makeEspArduino/makeEspArduino.mk:312: recipe for target 'erase_flash' failed
make: *** [erase_flash] Error 126
```

pls note the **Permission denied** error is due to the fact, that the path is:

`../../Arduino-ESP32-espressif/tools/esptool/esptool.py`

and not what it should be:

`ESPTOOL_PY = ../../Arduino-ESP32-everslick/tools/esptool.py`

**Comment by plerup** [comment]
Hrm, I'm a bit confused here. There is no variable named ESPTOOL_PY in the makefile.

**Comment by everslick** [comment]
so am i, it seems :-) has there been one at some point in time? or did I invent it entirely? LOL

**Comment by plerup** [comment]
:smiley: There was actually but that was for esp8266

**Comment by everslick** [comment]
AHH OK! I'm relieved :-D ...  Anyway. Setting ESPTOOL_PY obviously had no effect in later versions then and I guess makeEspArduino happily picked up the correct esptool path for me. but in this case it does not, it seems. works for you - i guess?

**Comment by plerup** [comment]
Well, there is a difference for flash and erase_flash. This is bit of a mess really, all due to trying to handle both old esptool and esptool.py. 
Try setting ESPTOOL_COM to the correct path of your own esptool.py

**Comment by everslick** [comment]
> Try setting ESPTOOL_COM to the correct path of your own esptool.py

that did the trick. :-) thanks!
