### ISSUE TITLE
make flash_fs fails

### ISSUE THREAD

**Issue by riban-bw** [plerup/makeEspArduino#96]
make flash_fs fails on my Cygwin installation with Arduino 1.8.7 because it finds the folder 0.2.0 which contains the mkspiffs.exe tool, not the tool itself.

**Comment by hannasm** [comment]
I am on debian and having the same issue with a 0.2.0 version of mkspiffs and a recently installed version of the arduino ide.

A quickfix was to change:

`
MKSPIFFS_PATH := $(lastword $(wildcard $(ARDUINO_ESP_ROOT)/tools/mkspiffs/*))
MKSPIFFS_PATH := $(lastword $(wildcard $(ESP_ROOT)/tools/mkspiffs/*))
`

to


`
MKSPIFFS_PATH := $(lastword $(wildcard $(ARDUINO_ESP_ROOT)/tools/mkspiffs/*/*))
MKSPIFFS_PATH := $(lastword $(wildcard $(ESP_ROOT)/tools/mkspiffs/*/*))
`

I checked blame and it didn't look like anything changed with the makefile code, so perhaps there was a packaging change in mkspiffs / esp8266 / arduino ide?

**Comment by hannasm** [comment]
Also, the error message i was getting:

```
Generating filesystem image: /home/hannasm/devel/FS.spiffs                                                             
/bin/sh: 1: /home/hannasm/.arduino15/packages/esp8266/tools/mkspiffs/0.2.0: Permission denied
```

**Comment by plerup** [comment]
Yes, just realized that the structure is different in Arduino environment and git clone.
Will be fixed.

**Comment by plerup** [comment]
Try latest commiot
